spring:
  application:
    name: demo-server    #nacos 服务名称 如果使用了微服务框架，则需要配置该属性
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:active-dev}
    include:
      - include-activiti
    group:
      active-lhy:
        - include-datasource-dev  #数据库
        - include-logging-dev     #日志
      active-dev:
        - include-datasource-dev  #数据库
        - include-logging-dev     #日志
      active-prod: #湛江中越能源生产环境
        - include-datasource-prod  #数据库
        - include-logging-prod      #日志