spring:
  jmx:
    enabled: false
  # ================================================
  #             datasource数据库设定
  # ================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # oracle数据库配置
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: tspquanquyu2021
    password: zngk*168#Zy
  jpa:
    #    hibernate:
    #      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        ddl-auto: update
        hbm2ddl:
          auto: update