spring:
  # ================================================
  #             tomcat多域名-数据库重名支持
  # ================================================
  jmx:
    enabled: false
  # ================================================
  #             datasource数据库设定
  # ================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver #oracle.jdbc.driver.OracleDriver #com.mysql.jdbc.Driver
    url: jdbc:oracle:thin:@192.168.2.7:1521:RHORCL
    username: ZYNY_RL
    password: 123
  jpa:
    #    hibernate:
    #      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        ddl-auto: update
        hbm2ddl:
          auto: update
  data:
    cassandra:
      ssl: false