spring:
  activiti:
#    process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes: .bpmn
    # 数据源指定
#    database-schema: ACTIVITI
    # 建表规则： 服务启动时检查数据库表，不存在则创建
    database-schema-update: true
    # 表示哪种情况下使用历史表，这里配置为all表示全部记录历史，方便绘制流程图; 记录历史等级 可配置的历史级别有none, acitivity, audit, full
    history-level: full
    # 表示使用历史表，如果不配置，则工程启动后可以检查数据库
    db-history-used: true
    # spring jpa使用
    jpa-enabled: true
    # 暂时不检查
    check-process-definitions: false
#    db-identity-used: true

